# Generated by Django 3.2 on 2023-03-14 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='company')),
                ('call_us', models.CharField(max_length=20)),
                ('email_us', models.CharField(max_length=20)),
                ('about', models.TextField(max_length=200)),
                ('fb_link', models.URLField(blank=True, null=True)),
                ('tw_link', models.URLField(blank=True, null=True)),
                ('insta_link', models.URLField(blank=True, null=True)),
                ('email', models.TextField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('phones', models.TextField(max_length=50)),
            ],
        ),
    ]
