# Generated by Django 4.1.7 on 2023-06-24 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_rename_order_cartdetail_cart"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cartdetail",
            old_name="quantiy",
            new_name="quantity",
        ),
        migrations.AddField(
            model_name="oredrdetail",
            name="total",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
